/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SoftwareEngineering;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.DefaultListModel;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author DeRed
 */
public class LoginUI extends javax.swing.JFrame {

    /**
     * Creates new form LoginUI
     */

    private final Border borderc ;
    private DefaultListModel<String> dlm = new DefaultListModel<>();
    private Schedule AppointmentList = new Schedule();
    
    
    
    
    
    
    
    public LoginUI() {

        initComponents();
        borderc = this.LoginForm_Username.getBorder(); // USED FOR CREDENTIAL VALIDATION
        //this.loading_icon.setVisible(false);
        FillSchedule();
       // this.User_Home_LeftSide.add()
        

    }
    public LoginUI(int a) {

        initComponents();
        borderc = this.LoginForm_Username.getBorder(); // USED FOR CREDENTIAL VALIDATION        
        this.ErrorDialog.setVisible(true);
        this.ErrorDialog.requestFocus();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        User_MainMenu = new javax.swing.JFrame();
        User_Home_Panel = new javax.swing.JPanel();
        User_Home_Body = new javax.swing.JPanel();
        User_Home_LeftSide = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AppointmentTable = new javax.swing.JTable();
        User_Home_RightSide = new javax.swing.JPanel();
        User_MenuBar = new javax.swing.JMenuBar();
        User_Action_Menu = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        UserMenuBar_Display = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        Display_Patient_List = new javax.swing.JMenuItem();
        Display_Order_History = new javax.swing.JMenuItem();
        User_Profile_Menu = new javax.swing.JMenu();
        User_Profile_Options = new javax.swing.JMenuItem();
        User_Profile_Logout = new javax.swing.JMenuItem();
        ErrorDialog = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        LoginFrame = new javax.swing.JPanel();
        LoginForm = new javax.swing.JPanel();
        LoginForm_Username = new javax.swing.JTextField();
        LoginForm_Password = new javax.swing.JPasswordField();
        LoginForm_SubmitButton = new javax.swing.JButton();
        LoginForm_Image = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        loading_icon = new javax.swing.JLabel();

        User_MainMenu.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        User_MainMenu.setTitle("Αρχική Σελίδα Γραμματέας");
        User_MainMenu.setMinimumSize(new java.awt.Dimension(1024, 720));
        User_MainMenu.setResizable(false);
        User_MainMenu.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                User_MainMenuWindowClosed(evt);
            }
        });

        User_Home_Panel.setBackground(new java.awt.Color(204, 204, 255));

        User_Home_Body.setBackground(new java.awt.Color(153, 153, 153));
        User_Home_Body.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        User_Home_Body.setForeground(new java.awt.Color(204, 204, 255));

        User_Home_LeftSide.setBackground(new java.awt.Color(255, 255, 255));
        User_Home_LeftSide.setPreferredSize(new java.awt.Dimension(505, 630));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ΣΗΜΕΡΙΝΟ ΠΡΟΓΡΑΜΜΑ");
        jLabel1.setFocusable(false);
        jLabel1.setPreferredSize(new java.awt.Dimension(505, 19));

        AppointmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(AppointmentTable);

        javax.swing.GroupLayout User_Home_LeftSideLayout = new javax.swing.GroupLayout(User_Home_LeftSide);
        User_Home_LeftSide.setLayout(User_Home_LeftSideLayout);
        User_Home_LeftSideLayout.setHorizontalGroup(
            User_Home_LeftSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, User_Home_LeftSideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        User_Home_LeftSideLayout.setVerticalGroup(
            User_Home_LeftSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(User_Home_LeftSideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1))
        );

        User_Home_RightSide.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout User_Home_RightSideLayout = new javax.swing.GroupLayout(User_Home_RightSide);
        User_Home_RightSide.setLayout(User_Home_RightSideLayout);
        User_Home_RightSideLayout.setHorizontalGroup(
            User_Home_RightSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );
        User_Home_RightSideLayout.setVerticalGroup(
            User_Home_RightSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 697, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout User_Home_BodyLayout = new javax.swing.GroupLayout(User_Home_Body);
        User_Home_Body.setLayout(User_Home_BodyLayout);
        User_Home_BodyLayout.setHorizontalGroup(
            User_Home_BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(User_Home_BodyLayout.createSequentialGroup()
                .addComponent(User_Home_LeftSide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(User_Home_RightSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        User_Home_BodyLayout.setVerticalGroup(
            User_Home_BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(User_Home_LeftSide, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
            .addComponent(User_Home_RightSide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout User_Home_PanelLayout = new javax.swing.GroupLayout(User_Home_Panel);
        User_Home_Panel.setLayout(User_Home_PanelLayout);
        User_Home_PanelLayout.setHorizontalGroup(
            User_Home_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(User_Home_Body, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        User_Home_PanelLayout.setVerticalGroup(
            User_Home_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(User_Home_Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        User_MenuBar.setBackground(new java.awt.Color(153, 153, 153));
        User_MenuBar.setForeground(new java.awt.Color(255, 255, 255));

        User_Action_Menu.setText("Επιλογές");

        jMenu1.setText("Δημιουργία");

        jMenuItem3.setText("Ραντεβού");
        jMenu1.add(jMenuItem3);

        jMenuItem1.setText("Ασθενής");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Παραγγελία");
        jMenu1.add(jMenuItem2);

        User_Action_Menu.add(jMenu1);

        UserMenuBar_Display.setText("Προβολή");

        jMenuItem4.setText("Πρόγραμμα Ραντεβού");
        UserMenuBar_Display.add(jMenuItem4);

        Display_Patient_List.setText("Λίστα Ασθενών");
        UserMenuBar_Display.add(Display_Patient_List);

        Display_Order_History.setText("Ιστορικό Παραγγελιών");
        UserMenuBar_Display.add(Display_Order_History);

        User_Action_Menu.add(UserMenuBar_Display);

        User_MenuBar.add(User_Action_Menu);

        User_Profile_Menu.setText("\"User\"");
        User_Profile_Menu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        User_Profile_Menu.setIconTextGap(0);

        User_Profile_Options.setText("Eπιλογές");
        User_Profile_Options.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_Profile_OptionsActionPerformed(evt);
            }
        });
        User_Profile_Menu.add(User_Profile_Options);

        User_Profile_Logout.setText("Αποσύνδεση");
        User_Profile_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_Profile_LogoutActionPerformed(evt);
            }
        });
        User_Profile_Menu.add(User_Profile_Logout);

        User_MenuBar.add(Box.createHorizontalGlue());

        User_MenuBar.add(User_Profile_Menu);

        User_MainMenu.setJMenuBar(User_MenuBar);

        javax.swing.GroupLayout User_MainMenuLayout = new javax.swing.GroupLayout(User_MainMenu.getContentPane());
        User_MainMenu.getContentPane().setLayout(User_MainMenuLayout);
        User_MainMenuLayout.setHorizontalGroup(
            User_MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(User_Home_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        User_MainMenuLayout.setVerticalGroup(
            User_MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(User_Home_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ErrorDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        ErrorDialog.setTitle("Error");
        ErrorDialog.setResizable(false);
        ErrorDialog.setSize(new java.awt.Dimension(456, 90));
        ErrorDialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                ErrorDialogWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Could not find \"config.ini\" in the application folder! Program will now terminate.");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout ErrorDialogLayout = new javax.swing.GroupLayout(ErrorDialog.getContentPane());
        ErrorDialog.getContentPane().setLayout(ErrorDialogLayout);
        ErrorDialogLayout.setHorizontalGroup(
            ErrorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ErrorDialogLayout.setVerticalGroup(
            ErrorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ιατρικό Γραφείο");
        setBackground(new java.awt.Color(204, 204, 255));
        setName("LoginWindow"); // NOI18N

        LoginFrame.setBackground(new java.awt.Color(204, 204, 255));
        LoginFrame.setForeground(new java.awt.Color(204, 204, 255));
        LoginFrame.setAlignmentX(0.0F);
        LoginFrame.setAlignmentY(0.0F);

        LoginForm.setBackground(new java.awt.Color(255, 255, 255));
        javax.swing.border.SoftBevelBorder border = new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED);
        LoginForm.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        LoginForm.setForeground(new java.awt.Color(255, 255, 255));

        LoginForm_Username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        LoginForm_Username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LoginForm_UsernameFocusGained(evt);
            }
        });

        LoginForm_Password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        LoginForm_Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LoginForm_PasswordFocusGained(evt);
            }
        });

        LoginForm_SubmitButton.setText("Σύνδεση");
        LoginForm_SubmitButton.setBorder(new javax.swing.border.MatteBorder(null));
        LoginForm_SubmitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginForm_SubmitButtonMouseClicked(evt);
            }
        });
        LoginForm_SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginForm_SubmitButtonActionPerformed(evt);
            }
        });

        LoginForm_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Avatar.png"))); // NOI18N

        UsernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UsernameLabel.setText("Όνομα Χρήστη");

        PasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PasswordLabel.setText("Κωδικός Πρόσβασης");
        PasswordLabel.setToolTipText("");

        loading_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loading_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/loader.gif"))); // NOI18N
        loading_icon.setDisabledIcon(null);
        loading_icon.setFocusable(false);

        javax.swing.GroupLayout LoginFormLayout = new javax.swing.GroupLayout(LoginForm);
        LoginForm.setLayout(LoginFormLayout);
        LoginFormLayout.setHorizontalGroup(
            LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginFormLayout.createSequentialGroup()
                .addGroup(LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginFormLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LoginForm_Image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LoginForm_Password, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LoginForm_Username, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LoginForm_SubmitButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UsernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(LoginFormLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(loading_icon)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        LoginFormLayout.setVerticalGroup(
            LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginFormLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(LoginForm_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoginForm_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoginForm_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LoginForm_SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loading_icon)
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout LoginFrameLayout = new javax.swing.GroupLayout(LoginFrame);
        LoginFrame.setLayout(LoginFrameLayout);
        LoginFrameLayout.setHorizontalGroup(
            LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginFrameLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(LoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        LoginFrameLayout.setVerticalGroup(
            LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginFrameLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(LoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        //jPanel1.setBounds(0,0,new_Height,new_Width*100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void FillSchedule(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ΩΡΑ");
        model.addColumn("ΑΣΘΕΝΗΣ");
        model.addColumn("ΙΑΤΡΟΣ");
        
        ArrayList<Appointment> list = AppointmentList.getSchedule();
        
        for ( Appointment x : list){
            model.addRow(new Object[]{x.getDate(), x.getPetient().getName(), x.getDoctorId()});
        } 
        
        this.AppointmentTable.setModel(model);
    }
    
    private boolean isUserInputValid(){
        boolean flag =true;
        if (this.LoginForm_Username.getText().equals("") || (!(this.LoginForm_Username.getText().matches("^[a-zA-Z0-9]+$")))){
            this.LoginForm_Username.setBorder(BorderFactory.createLineBorder(Color.red)); 
            flag = false;
        }

        if (this.LoginForm_Password.getPassword().length < 6){
            //this.passworderror.setVisible(true);
            this.LoginForm_Password.setBorder(BorderFactory.createLineBorder(Color.red));
            flag=false;
        }
        return flag;
    }
    private void LoginForm_SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginForm_SubmitButtonActionPerformed
  
    
        if (this.isUserInputValid() == true){
            this.loading_icon.setVisible(true);
            //TODO LOGIN

            this.setVisible(false); // HIDE LOGIN WINDOW
            //this.User_MainMenu.setExtendedState(JFrame.MAXIMIZED_BOTH); // MAXIMIZE WINDOW
            //Dimension body = this.User_Home_Body.getSize();
            // this.User_Home_RightSide.setSize(body.width/2, body.height);
            
            
            
            
            
            this.User_MainMenu.setVisible(true); // SHOW HOME SCREEN
            
            
            
        }

    }//GEN-LAST:event_LoginForm_SubmitButtonActionPerformed

    private void LoginForm_SubmitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginForm_SubmitButtonMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_LoginForm_SubmitButtonMouseClicked

    private void LoginForm_UsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LoginForm_UsernameFocusGained
        // TODO add your handling code here:
        this.LoginForm_Username.setBorder(borderc);
    }//GEN-LAST:event_LoginForm_UsernameFocusGained

    private void LoginForm_PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LoginForm_PasswordFocusGained
        // TODO add your handling code here:
        this.LoginForm_Password.setBorder(borderc);
        //this.passworderror.setVisible(false);
    }//GEN-LAST:event_LoginForm_PasswordFocusGained

    private void User_Profile_OptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_Profile_OptionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_User_Profile_OptionsActionPerformed

    private void User_Profile_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_Profile_LogoutActionPerformed
        //SYNC CHANGES WITH SERVER
        //CLOSE SOCKET
        //DISPOSE FRAME
        this.User_MainMenu.setVisible(false);
        dlm = new DefaultListModel<>();
       // this.User_Home_Calendar.setModel(dlm);
        
        
        this.setVisible(true);
        
    }//GEN-LAST:event_User_Profile_LogoutActionPerformed

    private void User_MainMenuWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_User_MainMenuWindowClosed
        // TODO add your handling code here:
        this.setVisible(true);
    }//GEN-LAST:event_User_MainMenuWindowClosed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ErrorDialogWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_ErrorDialogWindowClosed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ErrorDialogWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        if (MedicalOffice.ConfigFileExists() == false){
            java.awt.EventQueue.invokeLater(() -> {
            new LoginUI(1);
            
            });
        }
        else {
        
        java.awt.EventQueue.invokeLater(() -> {
            new LoginUI().setVisible(true);
        });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AppointmentTable;
    private javax.swing.JMenuItem Display_Order_History;
    private javax.swing.JMenuItem Display_Patient_List;
    private javax.swing.JDialog ErrorDialog;
    private javax.swing.JPanel LoginForm;
    private javax.swing.JLabel LoginForm_Image;
    private javax.swing.JPasswordField LoginForm_Password;
    private javax.swing.JButton LoginForm_SubmitButton;
    private javax.swing.JTextField LoginForm_Username;
    private javax.swing.JPanel LoginFrame;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JMenu UserMenuBar_Display;
    private javax.swing.JMenu User_Action_Menu;
    private javax.swing.JPanel User_Home_Body;
    private javax.swing.JPanel User_Home_LeftSide;
    private javax.swing.JPanel User_Home_Panel;
    private javax.swing.JPanel User_Home_RightSide;
    private javax.swing.JFrame User_MainMenu;
    private javax.swing.JMenuBar User_MenuBar;
    private javax.swing.JMenuItem User_Profile_Logout;
    private javax.swing.JMenu User_Profile_Menu;
    private javax.swing.JMenuItem User_Profile_Options;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel loading_icon;
    // End of variables declaration//GEN-END:variables
}
